//create a user public
###
POST http://127.0.0.1:5000/api/register
Content-Type: application/json

{
    "username": "carlos",
    "email": "carlos@gmail.com",
    "password": "123456"
}

###
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
    "email": "joao@gmail.com",
    "password": "123456"
}

###
GET http://127.0.0.1:5000/api/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjM0NzEyOTcyfQ.sg-cs45TxiJGM_CDYPbtjW6Xl4s62R6fAHPEENipmZg
###
POST http://127.0.0.1:5000/api/movie/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjM0ODg2NjIyfQ.NogEFsX1eUqPwvCw5aJjN_kW_QSl5leYEJ5OJ9OXO98

{
    "title": "Destroyer",
    "description": "A epic movie",
    "genre": "Action"
}

###
POST http://127.0.0.1:5000/api/user/1/movie/3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjM0ODg2NjIyfQ.NogEFsX1eUqPwvCw5aJjN_kW_QSl5leYEJ5OJ9OXO98

###
GET http://127.0.0.1:5000/api/user/1/movie
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNjM0ODg2NjIyfQ.NogEFsX1eUqPwvCw5aJjN_kW_QSl5leYEJ5OJ9OXO98